---
title: "Data report"
author: "Angelina Venetto"
date: "3/31/2022"
output: html_document
---

```{r setup, include=FALSE}
install.packages("tidytuesdayR")\
(library)tidyverse::
```
```{r setup, include=FALSE}
library(tidytuesdayR)
library(tidyverse)
```

```{r}
chocolate <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-18/chocolate.csv')
```
#This project aims to examine which country in north america manufactures the highest rated chocolate in the last 5 years 
#Data was found here: https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-18/readme.md

```{r}
ggplot(chocolate) +
  aes(x = country_of_bean_origin,
      y = rating,
      fill = rating,
      color = rating) +
  geom_point() 
```
#Filtering data from the last 5 years, while dropping any data with out a rating. Also grouping by country
```{r}
chocolate_clean <- chocolate %>%
  select(year = review_date, country = company_location, rating = rating)
```
```{r}
rating <- "rating"
country <- "country"
year <- "year"
canada <- "canada"
U.S.A. <- "U.S.A."
mexico <- "mexico"
```
```{r}
chocolate_rates <- chocolate_clean %>% 
 filter(year %in% c(2021)) %>% 
  drop_na(country, rating) %>%
 group_by(country)%>%   
summarize(rating = mean(rating))
ungroup() %>%  
  select(country, year, rating) %>% 

  #filter(year %in% c(2017, 2018, 2019, 2020, 2021, 2022)) %>%

  #making the data set wider
pivot_wider(
   id_cols = country,
   names_from = (year), 
   values_from = rating,
   ) 
  #pivot_longer(
    #cols = country, year,
    #names_to = c("country"),
    
#values_to = "year"
 
chocolate_rates
```
```{r}
ggplot(chocolate_rates) +
  aes( x = rating,
    y = country, 
      color = country,
      fill= country
   ) +
  geom_point() 
```
